export const ROLE_PERMISSIONS_MOCK = {
  SuperAdmin: {
    Dashboard: 'Full',
    Users: 'Full',
    RolesAndPermissions: 'Full',
    Agencies: 'Full',
    Agents: 'Full',
    Leads: 'Full',
    Buyers: 'Full',
    Sellers: 'Full',
    Properties: 'Full',
    Projects: 'Full',
    PropertyUnits: 'Full',
    SiteVisits: 'Full',
    FollowUps: 'Full',
    Calls: 'Full',
    WhatsApp: 'Full',
    Email: 'Full',
    Deals: 'Full',
    Bookings: 'Full',
    Payments: 'Full',
    Installments: 'Full',
    Documents: 'Full',
        Reports: 'Full',
    AuditLogs: 'Full',
    Settings: 'Full',
    Profile: 'Full'
  },
  Staff: {
    Dashboard: 'Manage',
    Users: 'View',
    RolesAndPermissions: 'None',
    Agencies: 'Manage',
    Agents: 'Manage',
    Leads: 'Manage',
    Buyers: 'Manage',
    Sellers: 'Manage',
    Properties: 'Manage',
    Projects: 'Manage',
    PropertyUnits: 'Manage',
    SiteVisits: 'Manage',
    FollowUps: 'Manage',
    Calls: 'Manage',
    WhatsApp: 'Manage',
    Email: 'Manage',
    Deals: 'Manage',
    Bookings: 'Manage',
    Payments: 'Manage',
    Installments: 'Manage',
    Documents: 'Manage',
        Reports: 'Manage',
    AuditLogs: 'View',
    Settings: 'None',
    Profile: 'Full'
  },
  Agency: {
    Dashboard: 'Manage',
    Users: 'None',
    RolesAndPermissions: 'None',
    Agencies: 'Own',
    Agents: 'Own',
    Leads: 'Own Agency',
    Buyers: 'Own Agency',
    Sellers: 'Own Agency',
    Properties: 'Own Agency',
    Projects: 'Own Agency',
    PropertyUnits: 'Own Agency',
    SiteVisits: 'Own Agency',
    FollowUps: 'Own Agency',
    Calls: 'Own Agency',
    WhatsApp: 'Own Agency',
    Email: 'Own Agency',
    Deals: 'Own Agency',
    Bookings: 'Own Agency',
    Payments: 'Own Agency',
    Installments: 'Own Agency',
    Documents: 'Own Agency',
        Reports: 'Own Agency',
    AuditLogs: 'None',
    Settings: 'Own Agency',
    Profile: 'Full'
  },
  Agent: {
    Dashboard: 'Own',
    Users: 'None',
    RolesAndPermissions: 'None',
    Agencies: 'View',
    Agents: 'View',
    Leads: 'Own',
    Buyers: 'Own',
    Sellers: 'Own',
    Properties: 'Assigned',
    Projects: 'View',
    PropertyUnits: 'Assigned',
    SiteVisits: 'Own',
    FollowUps: 'Own',
    Calls: 'Own',
    WhatsApp: 'Own',
    Email: 'Own',
    Deals: 'Own',
    Bookings: 'Own',
    Payments: 'View',
    Installments: 'View',
    Documents: 'Own',
        Reports: 'Own',
    AuditLogs: 'None',
    Settings: 'Own Profile',
    Profile: 'Full'
  },
  User: {
    Dashboard: 'Own',
    Users: 'None',
    RolesAndPermissions: 'None',
    Agencies: 'None',
    Agents: 'None',
    Leads: 'Own',
    Buyers: 'Own',
    Sellers: 'None',
    Properties: 'View',
    Projects: 'View',
    PropertyUnits: 'View',
    SiteVisits: 'Own',
    FollowUps: 'Own',
    Calls: 'None',
    WhatsApp: 'None',
    Email: 'None',
    Deals: 'View',
    Bookings: 'Own',
    Payments: 'Own',
    Installments: 'Own',
    Documents: 'Own',
        Reports: 'Own',
    AuditLogs: 'None',
    Settings: 'Own Profile',
    Profile: 'Full'
  }
};

export default ROLE_PERMISSIONS_MOCK;
